version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: echo "hello world"
