version: 2.0

jobs:
  python27:
    docker:
      # nox got issues with python 2.7 but it can still be used ot test 2.7
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 'export NOX_PYTHON_VERSIONS=2.7' >> $BASH_ENV
      - run: sudo pip install nox
      - run: nox
  python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 'export NOX_PYTHON_VERSIONS=3.6' >> $BASH_ENV
      - run: sudo pip install nox
      - run: nox
  python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: echo 'export NOX_PYTHON_VERSIONS=3.7' >> $BASH_ENV
      - run: sudo pip install nox
      - run: nox
  
  deploy-website:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Install node_modules
          command: |
            cd hydra/website
            yarn --no-progress
      - deploy:
          name: Publish gh-pages
          command: cd website && yarn install && GIT_USER=omry yarn deploy            

workflows:
  version: 2
  build:
    jobs:
      - python27
      - python36
      - python37
      - deploy-website:
          filters:
            branches:
              only: master  