# @package _group_

version: 1
formatters:
  simple:
    format: "[%(asctime)s][HYDRA] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  handlers: [console]

loggers:
  hydra:
    level: INFO
  hydra_plugins:
    level: INFO

disable_existing_loggers: false
